require 'active_record'
require 'yaml'
require 'logger'

task :default => :migrate

desc "Migrate the database through scripts in migrations/"
task :migrate => :environment do
	ActiveRecord::Migrator.migrate('migrations', ENV["VERSION"] ? ENV["VERSION"].to_i : nil )
end

task :environment do
	ActiveRecord::Base.establish_connection(YAML::load(File.open('database.yaml')))
	ActiveRecord::Base.logger = Logger.new(STDOUT)
end
